version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code is present
          command: |
                ls -al
                echo '^^ that is the codebase!' 

